<?xml version="1.0" encoding="utf-8"?><Database Name="KiemKeTaiSan" Class="kktsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-0KAI17V;Initial Catalog=KiemKeTaiSan;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="KiemKeTaiSanConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiTietThietBi" Member="ChiTietThietBis">
    <Type Name="ChiTietThietBi">
      <Column Name="MaCTTB" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTB" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenCTTB" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="GiaTienCTTB" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThietBi" Member="ThietBis">
    <Type Name="ThietBi">
      <Column Name="MaTB" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaLoaiTB" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenTB" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GiaTienTB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhuVucPhong" Member="KhuVucPhongs">
    <Type Name="KhuVucPhong">
      <Column Name="MaKV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenKV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiPhong" Member="LoaiPhongs">
    <Type Name="LoaiPhong">
      <Column Name="MaLP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLP" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiThietBi" Member="LoaiThietBis">
    <Type Name="LoaiThietBi">
      <Column Name="MaLoaiTB" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiTB" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Phong" Member="Phongs">
    <Type Name="Phong">
      <Column Name="MaPhong" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaLP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaKV" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenPhong" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>